#:import os os

<FullVal>

    on_enter:
        spinner.active = True
        self.start_test()


    MDBoxLayout:
        orientation: "vertical"
        adaptive_height: True
        pos_hint: {"top": 1}
        spacing: "30dp"
        id: main_layout

        MDBoxLayout:
            orientation: "vertical"
            adaptive_height: True
            spacing: "20dp"

            MDTopAppBar:
                title: "Full Validation Benchmark: "
                id: model_bar
                pos_hint: {"center_x": .5, "center_y": .75}
                background_palette: "Teal"
                background_hue: "500"

            MDTopAppBar:
                id: cases_bar
                title: "Cases: "
                md_bg_color: app.theme_cls.bg_light
                specific_text_color: app.theme_cls.text_color

            MDTopAppBar:
                title: "Time: "
                id: timer_bar
                pos_hint: {"center_x": .5, "center_y": .75}
                background_hue: "500"

            MDLabel:
                id: awad_status
                halign: "center"
                text: "Contacting Detection Prog..."

            MDProgressBar:
                id: progress_determinate
                value: 0


        MDSpinner:
            padding: "10dp"
            id: spinner
            size_hint: None, None
            size: "46dp", "46dp"
            pos_hint: {"center_x": .5}

        MDRaisedButton:
            id: backhome
            text: "Back"
            pos_hint: {"center_x": .5}
            on_release: self.parent.parent.go_back()
            
            